version: "3.8"
services:
  app:
    build: .
    ports:
      - "4500:4500"
    depends_on:
      - db
    volumes:
      - .:/app:z
#   db:
#     image: postgres:14.9-alpine3.18
#     restart: always
#     container_name: postgres-stackoverflow
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: spamdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
